import "./globals.css";
import "qweather-icons/font/qweather-icons.css"
import {ThemeProvider} from "next-themes";
import {WeatherContextProvider} from "@/context/WeatherContext";
import Head from "next/head";
import {SiTheweatherchannel} from "react-icons/si";
import {Toaster} from "@/components/ui/sonner";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`antialiased !p-4`}
        >
        <ThemeProvider attribute={"class"} defaultTheme={"system"} enableSystem>
            <WeatherContextProvider>
                <div className={"container h-full !m-auto !py-5 flex flex-col"}>
                    {children}
                </div>
            </WeatherContextProvider>
        </ThemeProvider>
        <Toaster />
        </body>
        </html>
    );
}
