import "./globals.css";
import {ThemeProvider} from "next-themes";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`antialiased !p-4`}
        >
        <ThemeProvider attribute={"class"} defaultTheme={"system"} enableSystem>
            <div className={"container !m-auto"}>
                {children}
            </div>
        </ThemeProvider>
        </body>
        </html>
    );
}
